### ISSUE TITLE
status bar and bottom tab are all inside safe area which result in huge space at top and bottom of screen

### ISSUE THREAD

**Issue by karpedm** [ivopr/tamagui-expo#49]
like this

![image](https://github.com/ivopr/tamagui-expo/assets/4716594/664dd70b-ce50-470e-b6c5-b234cd017e93)

**Comment by maxwellwachira** [comment]
I have  the same issue. Did you manage to solve?

**Comment by ivopr** [comment]
@karpedm @maxwellwachira hey there, my bad for taking so long, basically what happened here was:

1. SafeAreaView was wrapping all screens of the app, meaning things wouldn't render behind status and navigation bars.
2. React Native Navigation's (which Expo Router uses behind the scenes) default header component is thinking that we're not in a SafeAreaView, so its height is the status bar height + the needed height for the component.

I didn't really spent the time figuring out if the same applied for the tab bar (but I suppose so) as SafeAreaView is now used only on index screen.

But how does it explain the header in user page having the expected behavior? It was a custom component, not a stock one,as you can see [here](https://github.com/ivopr/tamagui-expo/blob/88293b5aa59f968c061a6a73edb0f6599b2a4c8d/app/users/%5Buser%5D.tsx#L17-L26).
