### ISSUE TITLE
Expo router

### ISSUE THREAD

**Issue by geoman2** [ivopr/tamagui-expo#7]
Hello

How hard is update the starter to the new expo router? Also, did you consider to add an auth system to the starter (supabase, planetscale or cockroach db would be fine)? A developer has created an auth system based on firebase, supabase or laravel sanctum https://youtu.be/bJTz7h3o44I?t=136 docs here https://quasar.vueauth.com/providers/
But it is vuejs based.

**Comment by ivopr** [comment]
Hello, first of all, thanks for dropping by here.
Since Expo Router is still in alpha I think that it is worth implementing on this repo for now (to be truthful, I didn't searched/studied the new router yet as it is too early, any API can change at any given time).
On ver 1.x of this template I've bloated it with MobX, MMKV and I18n, which forced you guys to build it if you wanted to get a glimpse of Tamagui on Expo only, on ver 2, I've debloated it and made a public build so the guys who just want to see some basic feel can open it in Expo Go and well, see it. Firebase would bring back the same problem that 1.x has (you wouldn't be able to see it in Expo Go). I'll check supabase tho, if it is possible to implement while remaining Expo Go compatible it'll make it here.

**Comment by ivopr** [comment]
Hey @geoman2, well, it took some months, but as we reached Expo Router v1 now it should be safe enough to start using it. I've finished migrating it to Expo Router some minutes ago and it is now up. Regarding the Auth flow, I've successfully implemented with supabase in another app I have here, but I think it is not the focus for this template, as it is easy enough to implement. So, as the major point of this issue was Expo Router and now it is done, I'll be closing this.
